# Generated by Django 5.2.7 on 2025-11-07 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False, verbose_name='店舗ID')),
                ('store_name', models.CharField(max_length=64, verbose_name='店舗名')),
                ('category', models.CharField(max_length=64, verbose_name='カテゴリ')),
                ('tel', models.CharField(blank=True, max_length=32, verbose_name='電話番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('open_hours', models.CharField(max_length=20, verbose_name='営業時間')),
                ('lat', models.FloatField(default=0.0, verbose_name='緯度')),
                ('lng', models.FloatField(default=0.0, verbose_name='経度')),
            ],
            options={
                'verbose_name': '加盟店',
                'verbose_name_plural': '加盟店',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_to_email', models.EmailField(max_length=100, verbose_name='返信先メールアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('subject', models.CharField(max_length=100, verbose_name='件名')),
                ('body_text', models.TextField(verbose_name='内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inquiries/', verbose_name='添付画像')),
                ('is_replied', models.BooleanField(default=False, verbose_name='返信済み')),
                ('reply_message', models.TextField(blank=True, verbose_name='返信内容')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='問い合わせユーザー')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('description', models.TextField(verbose_name='内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'AIレポート',
                'verbose_name_plural': 'AIレポート',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateField(auto_now_add=True, verbose_name='スキャン日時')),
                ('ocr_text', models.TextField(blank=True, verbose_name='文字起こし内容')),
                ('image_url', models.URLField(max_length=191, verbose_name='画像URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'レシート',
                'verbose_name_plural': 'レシート',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='タイトル')),
                ('description', models.CharField(max_length=64, verbose_name='詳細')),
                ('type', models.CharField(max_length=64, verbose_name='タイプ')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='割引量')),
                ('available_stores', models.ManyToManyField(blank=True, to='core.store', verbose_name='利用可能店舗')),
            ],
            options={
                'verbose_name': 'クーポン',
                'verbose_name_plural': 'クーポン',
            },
        ),
    ]
