# Generated by Django 5.2.7 on 2025-11-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True, verbose_name='解析データ'),
        ),
    ]
