# Generated by Django 5.2.7 on 2025-11-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='open_hours',
        ),
        migrations.AddField(
            model_name='store',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='閉店時間'),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開店時間'),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('restaurant', '飲食店'), ('retail', '小売店'), ('service', 'サービス業'), ('other', 'その他')], max_length=64, verbose_name='カテゴリ'),
        ),
    ]
