# Generated by Django 5.2.7 on 2025-11-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_receipt_parsed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='transaction_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取引日時'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True, verbose_name='解析済みデータ'),
        ),
    ]
