# Generated by Django 5.2.7 on 2025-10-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_inquiry_delete_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=64, verbose_name='店舗名')),
                ('category', models.CharField(max_length=64, verbose_name='カテゴリ')),
                ('tel', models.CharField(blank=True, max_length=32, verbose_name='電話番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('open_hours', models.CharField(max_length=20, verbose_name='営業時間')),
            ],
            options={
                'verbose_name': '加盟店',
                'verbose_name_plural': '加盟店',
            },
        ),
    ]
