# Generated by Django 5.2.7 on 2025-10-31 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateField(auto_now_add=True, verbose_name='スキャン日時')),
                ('ocr_text', models.TextField(blank=True, verbose_name='文字起こし内容')),
                ('image_url', models.URLField(max_length=191, verbose_name='画像URL')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.store', verbose_name='店舗')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'レシート',
                'verbose_name_plural': 'レシート',
            },
        ),
    ]
