# Generated by Django 5.2.7 on 2025-11-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_receipt_transaction_time_alter_receipt_parsed_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='image',
        ),
        migrations.AddField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='announcements/', verbose_name='ファイル'),
        ),
    ]
