# Generated by Django 5.2.7 on 2025-11-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_alter_coupon_type_receiptitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='エコ商品名/キーワード')),
                ('jan_code', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='JANコード')),
                ('points', models.IntegerField(default=10, verbose_name='付与ポイント')),
            ],
            options={
                'verbose_name': 'エコ商品',
                'verbose_name_plural': 'エコ商品',
            },
        ),
    ]
