# Generated by Django 5.2.7 on 2025-10-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='タイトル')),
                ('description', models.CharField(max_length=64, verbose_name='詳細')),
                ('type', models.CharField(max_length=64, verbose_name='タイプ')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='割引量')),
                ('available_stores', models.ManyToManyField(blank=True, to='core.store', verbose_name='利用可能店舗')),
            ],
            options={
                'verbose_name': 'クーポン',
                'verbose_name_plural': 'クーポン',
            },
        ),
    ]
