# Generated by Django 5.2.7 on 2025-11-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ecoproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='requirement',
            field=models.CharField(blank=True, max_length=255, verbose_name='利用条件'),
        ),
    ]
