# Generated by Django 5.2.7 on 2025-11-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_coupon_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='points_earned',
            field=models.IntegerField(default=0, verbose_name='獲得ポイント'),
        ),
    ]
