# Generated by Django 5.2.7 on 2025-11-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inquiries/', verbose_name='添付画像'),
        ),
    ]
