# Generated by Django 5.2.7 on 2025-11-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_inquiry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='返信済み'),
        ),
    ]
