# Generated by Django 5.2.7 on 2025-11-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('unanswered', '未対応'), ('in_progress', '対応中'), ('completed', '完了')], default='unanswered', max_length=20, verbose_name='ステータス'),
        ),
    ]
