# Generated by Django 5.2.7 on 2025-11-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inquiry_is_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='reply_message',
            field=models.TextField(blank=True, verbose_name='返信内容'),
        ),
    ]
