# Generated by Django 5.2.7 on 2025-11-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_inquiry_reply_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='lat',
            field=models.FloatField(default=0.0, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='store',
            name='lng',
            field=models.FloatField(default=0.0, verbose_name='経度'),
        ),
    ]
