# Generated by Django 5.2.7 on 2025-11-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_inquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='score',
            field=models.IntegerField(default=0, verbose_name='スコア'),
        ),
    ]
