# Generated by Django 5.2.7 on 2026-01-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_report_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='points',
            field=models.IntegerField(default=0, verbose_name='獲得ポイント'),
        ),
    ]
