# Generated by Django 5.2.7 on 2026-01-13 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_receiptitem_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('admin', '管理者'), ('user', 'ユーザー')], max_length=10, verbose_name='送信者タイプ')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.inquiry', verbose_name='お問い合わせ')),
            ],
            options={
                'verbose_name': 'お問い合わせメッセージ',
                'verbose_name_plural': 'お問い合わせメッセージ',
            },
        ),
    ]
