# Generated by Django 5.2.7 on 2026-01-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_inquirymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='required_points',
            field=models.IntegerField(default=0, verbose_name='必要ポイント数'),
        ),
    ]
