# Generated by Django 5.2.7 on 2026-01-14 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_coupon_required_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('rejected', '却下')], default='approved', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_coupons', to='core.store', verbose_name='作成店舗'),
        ),
        migrations.AddField(
            model_name='ecoproduct',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='ecoproduct',
            name='status',
            field=models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('rejected', '却下')], default='approved', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AddField(
            model_name='ecoproduct',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.store', verbose_name='店舗'),
        ),
    ]
