# Generated by Django 5.2.7 on 2026-01-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_coupon_remarks_coupon_status_coupon_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='monthly_points',
            field=models.IntegerField(default=0, verbose_name='月間獲得ポイント'),
        ),
        migrations.AddField(
            model_name='report',
            name='rank',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='会員ランク'),
        ),
    ]
