# Generated by Django 5.2.7 on 2026-01-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_report_monthly_points_report_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoproduct',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='共通商品'),
        ),
    ]
