# Generated by Django 5.2.7 on 2026-01-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ecoproduct_is_common'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('rejected', '却下'), ('deletion_requested', '削除申請中')], default='approved', max_length=20, verbose_name='ステータス'),
        ),
    ]
