# Generated by Django 5.2.7 on 2026-01-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_coupon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='却下理由'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='ecoproduct',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='却下理由'),
        ),
        migrations.AddField(
            model_name='ecoproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
