# Generated by Django 5.2.7 on 2026-01-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_coupon_rejection_reason_coupon_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='held_points',
            field=models.IntegerField(default=0, verbose_name='その月の所持ポイント'),
        ),
    ]
