# Generated by Django 5.2.7 on 2025-11-06 05:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='必須。50文字以下。文字、数字、および @/./+/-/_ のみ使用できます。', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_verified', models.BooleanField(default=False, verbose_name='メール認証済み')),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='認証トークン')),
                ('current_points', models.IntegerField(default=0, verbose_name='ポイント')),
                ('rank', models.CharField(default='seed', max_length=10, verbose_name='ランク')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='アカウント更新日時')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('purchased_amount', models.IntegerField(default=0, verbose_name='購入点数')),
                ('lastmonth_point', models.IntegerField(default=0, verbose_name='先月獲得ポイント')),
                ('role', models.CharField(choices=[('system', 'システム管理者'), ('admin', '管理者'), ('store', '店舗'), ('user', '一般ユーザー')], default='user', max_length=10, verbose_name='役割')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
