# Generated by Django 5.2.7 on 2025-10-31 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_coupons',
            field=models.CharField(blank=True, max_length=30, verbose_name='所持クーポン'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_points',
            field=models.IntegerField(default=0, verbose_name='ポイント'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastmonth_point',
            field=models.IntegerField(default=0, verbose_name='先月獲得ポイント'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='purchased_amount',
            field=models.IntegerField(default=0, verbose_name='購入点数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.CharField(default='seed', max_length=10, verbose_name='ランク'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='アカウント更新日時'),
        ),
    ]
