# Generated by Django 5.2.7 on 2025-11-07 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_coupons',
            field=models.ManyToManyField(blank=True, to='core.coupon', verbose_name='所持クーポン'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.store', verbose_name='所属店舗'),
        ),
    ]
