# Generated by Django 5.2.7 on 2025-11-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_current_coupons_customuser_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', '管理者'), ('store', '店舗'), ('user', '一般ユーザー')], default='user', max_length=10, verbose_name='役割'),
        ),
    ]
