# Generated by Django 5.2.7 on 2025-11-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(choices=[('seed', '種'), ('sprout', '芽'), ('tree', '木'), ('apple_tree', 'リンゴの木')], default='seed', max_length=20, verbose_name='ランク'),
        ),
    ]
