# Generated by Django 5.2.7 on 2025-11-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_change_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='メール変更認証トークン'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='new email address'),
        ),
    ]
