# Generated by Django 5.2.7 on 2025-10-31 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_birthday_and_more'),
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('system', 'システム管理者'), ('admin', '管理者'), ('store', '店舗'), ('user', '一般ユーザー')], default='user', max_length=10, verbose_name='役割'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.store', verbose_name='所属店舗'),
        ),
    ]
