# Generated by Django 5.2.7 on 2025-10-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_role_customuser_store'),
        ('core', '0006_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current_coupons',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_coupons',
            field=models.ManyToManyField(blank=True, to='core.coupon', verbose_name='所持クーポン'),
        ),
    ]
