# Generated by Django 5.2.7 on 2026-01-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='withdrawal_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='退会確認コード'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='withdrawal_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退会確認コード有効期限'),
        ),
    ]
