# Generated by Django 5.2.7 on 2026-01-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_withdrawal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_reset_month',
            field=models.DateField(blank=True, null=True, verbose_name='最後にポイントリセットした月'),
        ),
    ]
